{{- if and .Values.toolhive.registry.enabled .Values.toolhive.registry.release.enabled }}
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: {{ printf "%s-toolhive-registry" .Release.Name }}
  namespace: {{ .Values.toolhive.registry.release.sourceNamespace }}
  labels:
    {{- include "connectool.labels" . | nindent 4 }}
spec:
  interval: 30m
  provider: generic
  url: oci://ghcr.io/stacklok/toolhive-registry-server
  ref:
    tag: {{ .Values.toolhive.registry.release.version | quote }}
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: toolhive-registry-server
  namespace: {{ .Values.toolhive.registry.release.sourceNamespace }}
  labels:
    {{- include "connectool.labels" . | nindent 4 }}
spec:
  interval: 30m
  releaseName: toolhive-registry-server
  targetNamespace: {{ .Values.toolhive.namespace }}
  storageNamespace: {{ .Values.toolhive.namespace }}
  chartRef:
    kind: OCIRepository
    name: {{ printf "%s-toolhive-registry" .Release.Name }}
  install:
    disableTakeOwnership: false
    remediation: {retries: 3}
  upgrade:
    disableTakeOwnership: false
    cleanupOnFail: true
    remediation: {retries: 3, strategy: rollback}
  rollback: {cleanupOnFail: true}
  values:
    {{- toYaml .Values.toolhive.registry.release.values | nindent 4 }}
{{- end }}
